//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists..
        /// </summary>
        internal static string lblAccoutContain {
            get {
                return ResourceManager.GetString("lblAccoutContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string lblConfirmPassIsvaild {
            get {
                return ResourceManager.GetString("lblConfirmPassIsvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string lblCreateNew {
            get {
                return ResourceManager.GetString("lblCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resest Password.
        /// </summary>
        internal static string lblResestPassword {
            get {
                return ResourceManager.GetString("lblResestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản đang bị khóa.
        /// </summary>
        internal static string MsgAccountIsLock {
            get {
                return ResourceManager.GetString("MsgAccountIsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản không Tồn tại.
        /// </summary>
        internal static string MsgAccountNotContain {
            get {
                return ResourceManager.GetString("MsgAccountNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu không đúng.
        /// </summary>
        internal static string MsgPassworkIsNotVaild {
            get {
                return ResourceManager.GetString("MsgPassworkIsNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản không đúng.
        /// </summary>
        internal static string MsgUserIsNotVaild {
            get {
                return ResourceManager.GetString("MsgUserIsNotVaild", resourceCulture);
            }
        }
    }
}
